base_config:
  - configs/variance.yaml

binary_data_dir: 'data/opencpop_duration/binary'

predict_dur: true
predict_pitch: false
predict_energy: false
predict_breathiness: true
predict_voicing: true
predict_tension: false

dur_prediction_args:
  arch: resnet
  hidden_size: 256
  dropout: 0.1
  num_layers: 5
  kernel_size: 3
  log_offset: 1.0
  loss_type: mse
  lambda_pdur_loss: 0.3
  lambda_wdur_loss: 1.0
  lambda_sdur_loss: 3.0

# train and eval
optimizer_args:
  optimizer_cls: torch.optim.AdamW
  lr: 0.0006
lr_scheduler_args:
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 5000
  gamma: 0.75

max_updates: 60000