diff_loss_type: l2_rf_norm

diffusion_type: 'RectifiedFlow' #ddpm

diff_accelerator: 'euler' # euler rk2 rk4 rk5 rk5_fp64 euler_fp64 rk4_fp64 rk2_fp64

T_start: 0
T_start_infer: 0
sampling_steps: 10
time_scale_factor: 1000

diff_speedup: 100
timestep_type: 'continuous' #discrete
loss_clip_min: 0.5